class mes:
    def __init__(self):
        self.dict = {"mes1": "can not start driving\n",
                         "mes2": "can not stop\n",
                         "mes3": "can not gearUp\n",
                         "mes4": "can not gearDown\n",
                         "mes5": "can not  refueling\n",
                         "mes6": "test_stop unsucceed\n",
                         "mes7": "test_stop succeed\n",
                          "mes8": "test_start unsucceed\n",
                           "mes16": "test_refueling_mony succeed\n",
                          "mes17": "test_refueling_mony unsucceed\n",
                           "mes9": "test_start succeed\n",
                           'mes10': "start succeed\n",
                           'mes11': "driving succeed\n",
                           'mes12': "stop succeed\n",
                           'mes13': "gearUp succeed\n",
                           'mes14': "gearDown succeed\n",
                           'mes15': "refueling succeed\n",
                            "mes18": "test_gearUp succeed\n",
                          "mes19": "test_gearUp unsucceed\n",
                               "mes20": "gearDown succeed\n",
                          "mes21": "gearDown unsucceed\n",
                          "mes22": "test_gear_less_than_min unsucceed\n",
                          "mes23": "test_gear_more_than_max unsucceed\n",
                           }
